services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tempus
    volumes:
      - pgdata:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686   # UI
      - 4317:4317     # OTLP gRPC
    environment:
      COLLECTOR_OTLP_ENABLED: true

volumes:
  pgdata: